### ISSUE TITLE
Question: Possible to join a RTP session?

### ISSUE THREAD

**Issue by microfx** [lathoub/Arduino-AppleMIDI-Library#78]
Hey!

The example shows how to initiate a RTP session. Is it also possible to join a MIDI session? I got a MIDI router which always has a few open which can be joined.

Stay safe! 

Cheers

**Comment by lathoub** [comment]
Have a look at the [InitiateSession ](https://github.com/lathoub/Arduino-AppleMIDI-Library/tree/master/examples/EthernetShield_InitiateSession)example

**Comment by microfx** [comment]
Reading the example... I can see no difference. Initiating is not joining an existing session, is it?

**Comment by lathoub** [comment]
Any other example then: https://github.com/lathoub/Arduino-AppleMIDI-Library/tree/master/examples/EthernetShield_NoteOnOffEverySec

**Comment by microfx** [comment]
So what‘s different here?

  // Create a session and wait for a remote host to connect to us

where is this another example? This is still the other way around?

**Comment by lathoub** [comment]
> I got a MIDI router which always has a few open which can be joined

Not sure how to answer, are you familiar with the RtpMidi (AppleMIDI) protocol?
Most examples wait for the **session initiator** to connect to the Arduino (Is your` MIDI router` a session initiator?)

**Comment by microfx** [comment]
Yes, my MIDI router is a session initiator. iConnectivity mio10. I use rtp MIDI all the time (connecting macOS/iOS to the sessions of the router)

**Comment by lathoub** [comment]
Then start with the [NoteOn/Off](https://github.com/lathoub/Arduino-AppleMIDI-Library/tree/master/examples/EthernetShield_NoteOnOffEverySec) example

**Comment by rockomatthews** [comment]
It is a slightly different experience and would seem like the other way around because you have to manually create the Arduino session.  Pretty sure what he is saying is he is expecting this connection step to look different.  My iPhone in the picture is "Projector Bach" since I use the app for MIDI Designer Pro 2 App on my iPhone.  With that, your device automatically appears in the "dictionary" after initiating a session on 5004.  Only difference is that there are steps described on how to add the Arduino in the comments.  But other things just pop up if that helps...


![IMG_5042](https://user-images.githubusercontent.com/3928985/79156658-e349ff80-7d98-11ea-8a0d-1476f84c055a.jpeg)

**Comment by lathoub** [comment]
Did you get it to work?

**Comment by lathoub** [comment]
Did you get it to work?
